### PR TITLE
Moving from CSS to LESS

### PR DESCRIPTION
**Pull request by tpoisot**
Following #9 -- I think think should be blocking #7 

I'll add a bunch of commits and then we can discuss whether to merge.

### CODE REVIEW

**Comment by tpoisot** [comment]
:memo: I need to rebase against master

**Comment by tpoisot** [comment]
:tada: REBASED

**Comment by lwasser** [comment]
@tpoisot lemme know if / when you're ready for this to be merged!

**Comment by tpoisot** [comment]
I am, just want you guys to confirm.

**Comment by lwasser** [comment]
?? -- is the caption style element still there? (you may have a better idea how to do this)
it was img + em {} 

Also -- how does the .less approach work. does the make file build a final css file from the css chunks in the .less files ? thx!

**Comment by jduckles** [comment]
I think this can roll in if you'd like.

**Comment by lwasser** [comment]
Cool – do you have super powers @jduckles ? if not I’ll merge but if you wanna merge go ahead.

My questions were only clarification so I understand the structure.

Leah

**Pull request merged**
